/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Window extends javax.swing.JFrame {

    private byte currentIndex;
    private boolean finish;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        this.currentIndex = 0;
        this.finish = false;
        this.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAtencion = new javax.swing.JLabel();
        jLabelDisponibilidad = new javax.swing.JLabel();
        jLabelActualizacion = new javax.swing.JLabel();
        jButtonReiniciar = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jPanelToScroll = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jPanelImage = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelAtencion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelAtencion.setText("Atención al cliente");

        jLabelDisponibilidad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelDisponibilidad.setText("Disponibilidad interna");

        jLabelActualizacion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelActualizacion.setText("Actualización de registros");

        jButtonReiniciar.setText("Reiniciar");
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonSiguiente.setText("Siguitente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jScrollPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImageLayout = new javax.swing.GroupLayout(jPanelImage);
        jPanelImage.setLayout(jPanelImageLayout);
        jPanelImageLayout.setHorizontalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        jPanelImageLayout.setVerticalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(jPanelImage);

        javax.swing.GroupLayout jPanelToScrollLayout = new javax.swing.GroupLayout(jPanelToScroll);
        jPanelToScroll.setLayout(jPanelToScrollLayout);
        jPanelToScrollLayout.setHorizontalGroup(
            jPanelToScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
            .addGroup(jPanelToScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelToScrollLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelToScrollLayout.setVerticalGroup(
            jPanelToScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(jPanelToScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelToScrollLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelAtencion)
                        .addGap(123, 123, 123)
                        .addComponent(jLabelDisponibilidad)
                        .addGap(120, 120, 120)
                        .addComponent(jLabelActualizacion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelToScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReiniciar)
                .addGap(113, 113, 113)
                .addComponent(jButtonAnterior)
                .addGap(18, 18, 18)
                .addComponent(jButtonSiguiente)
                .addGap(234, 234, 234))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAtencion)
                    .addComponent(jLabelDisponibilidad)
                    .addComponent(jLabelActualizacion))
                .addGap(18, 18, 18)
                .addComponent(jPanelToScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        if (!finish){
            this.currentIndex += 1;
            this.upDateImage();
            return;
        }
        
        this.finish = false;
        int option = JOptionPane.showConfirmDialog(null, 
                                                   "¿Quiere reiniciar el proceso?",
                                                   "Fin",
                                                   JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            this.currentIndex = 0;
            jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.png")));
            return;
        }
        if (option == JOptionPane.NO_OPTION) {
            this.currentIndex -= 1;
            return;
        }
        this.currentIndex -= 1;
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        if(this.currentIndex == 0){
            return;
        }
        this.currentIndex -= 1;
        this.finish = false;
        this.upDateImage();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed
        // TODO add your handling code here
        this.currentIndex = 0;
        this.finish = false;
        this.upDateImage();
    }//GEN-LAST:event_jButtonReiniciarActionPerformed
    
    private void upDateImage(){
        
        switch(this.currentIndex){
            case 0:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.png")));
                break;
            case 1:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png")));
                break;
            case 2:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png")));
                break;
            case 3:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png")));
                break;
            case 4:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png")));
                break;
            case 5:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png")));
                break;
            case 6:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png")));
                break;
            case 7:
                int option = JOptionPane.showConfirmDialog(null, 
                                                          "¿Es necesaria la visita técnica?",
                                                          "Decisión",
                                                          JOptionPane.YES_NO_OPTION);
                
                if (option == JOptionPane.YES_OPTION) {
                    jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/si.png")));
                    break;
                }
                if (option == JOptionPane.NO_OPTION) {
                    jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no.png")));
                    this.finish = true;
                    break;
                }
                this.currentIndex -= 1;
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png")));
                break;
            case 8:
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8.png")));
                this.finish = true;
                break;
            default:
                this.currentIndex = 0;
                jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.png")));
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelActualizacion;
    private javax.swing.JLabel jLabelAtencion;
    private javax.swing.JLabel jLabelDisponibilidad;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelToScroll;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
